#include "bot.hpp"

Bot::Bot()
{
    _jokes.push_back("Why don’t skeletons fight each other? They don’t have the guts!");
    _jokes.push_back("I told my wife she should embrace her mistakes. She gave me a hug.");
    _jokes.push_back("Parallel lines have so much in common. It’s a shame they’ll never meet.");
    _jokes.push_back("Why was the math book sad? It had too many problems.");
    _jokes.push_back("Why don’t programmers like nature? It has too many bugs.");
    _jokes.push_back("I told my computer I needed a break, and now it won’t stop sending me vacation ads.");
    _jokes.push_back("Why do cows have hooves instead of feet? Because they lactose.");
    _jokes.push_back("I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you...'");
    _jokes.push_back("What did the big flower say to the little flower? 'Hey, bud!'");
    _jokes.push_back("Why did the scarecrow win an award? Because he was outstanding in his field!");
	_capitals.push_back(std::make_pair("Afghanistan", "Kabul"));
    _capitals.push_back(std::make_pair("Albania", "Tirana"));
    _capitals.push_back(std::make_pair("Algeria", "Algiers"));
    _capitals.push_back(std::make_pair("Andorra", "Andorra la Vella"));
    _capitals.push_back(std::make_pair("Angola", "Luanda"));
    _capitals.push_back(std::make_pair("Antigua and Barbuda", "Saint John's"));
    _capitals.push_back(std::make_pair("Argentina", "Buenos Aires"));
    _capitals.push_back(std::make_pair("Armenia", "Yerevan"));
    _capitals.push_back(std::make_pair("Australia", "Canberra"));
    _capitals.push_back(std::make_pair("Austria", "Vienna"));
    _capitals.push_back(std::make_pair("Azerbaijan", "Baku"));
    _capitals.push_back(std::make_pair("Bahamas", "Nassau"));
    _capitals.push_back(std::make_pair("Bahrain", "Manama"));
    _capitals.push_back(std::make_pair("Bangladesh", "Dhaka"));
    _capitals.push_back(std::make_pair("Barbados", "Bridgetown"));
    _capitals.push_back(std::make_pair("Belarus", "Minsk"));
    _capitals.push_back(std::make_pair("Belgium", "Brussels"));
    _capitals.push_back(std::make_pair("Belize", "Belmopan"));
    _capitals.push_back(std::make_pair("Benin", "Porto-Novo"));
    _capitals.push_back(std::make_pair("Bhutan", "Thimphu"));
    _capitals.push_back(std::make_pair("Bolivia", "Sucre"));
    _capitals.push_back(std::make_pair("Bosnia and Herzegovina", "Sarajevo"));
    _capitals.push_back(std::make_pair("Botswana", "Gaborone"));
    _capitals.push_back(std::make_pair("Brazil", "Brasília"));
    _capitals.push_back(std::make_pair("Brunei", "Bandar Seri Begawan"));
    _capitals.push_back(std::make_pair("Bulgaria", "Sofia"));
    _capitals.push_back(std::make_pair("Burkina Faso", "Ouagadougou"));
    _capitals.push_back(std::make_pair("Burundi", "Gitega"));
    _capitals.push_back(std::make_pair("Cabo Verde", "Praia"));
    _capitals.push_back(std::make_pair("Cambodia", "Phnom Penh"));
    _capitals.push_back(std::make_pair("Cameroon", "Yaoundé"));
    _capitals.push_back(std::make_pair("Canada", "Ottawa"));
    _capitals.push_back(std::make_pair("Central African Republic", "Bangui"));
    _capitals.push_back(std::make_pair("Chad", "N'Djamena"));
    _capitals.push_back(std::make_pair("Chile", "Santiago"));
    _capitals.push_back(std::make_pair("China", "Beijing"));
    _capitals.push_back(std::make_pair("Colombia", "Bogotá"));
    _capitals.push_back(std::make_pair("Comoros", "Moroni"));
    _capitals.push_back(std::make_pair("Congo, Democratic Republic of the", "Kinshasa"));
    _capitals.push_back(std::make_pair("Congo, Republic of the", "Brazzaville"));
    _capitals.push_back(std::make_pair("Costa Rica", "San José"));
    _capitals.push_back(std::make_pair("Côte d'Ivoire", "Yamoussoukro"));
    _capitals.push_back(std::make_pair("Croatia", "Zagreb"));
    _capitals.push_back(std::make_pair("Cuba", "Havana"));
    _capitals.push_back(std::make_pair("Cyprus", "Nicosia"));
    _capitals.push_back(std::make_pair("Czech Republic", "Prague"));
    _capitals.push_back(std::make_pair("Denmark", "Copenhagen"));
    _capitals.push_back(std::make_pair("Djibouti", "Djibouti"));
    _capitals.push_back(std::make_pair("Dominica", "Roseau"));
    _capitals.push_back(std::make_pair("Dominican Republic", "Santo Domingo"));
    _capitals.push_back(std::make_pair("Ecuador", "Quito"));
    _capitals.push_back(std::make_pair("Egypt", "Cairo"));
    _capitals.push_back(std::make_pair("El Salvador", "San Salvador"));
    _capitals.push_back(std::make_pair("Equatorial Guinea", "Malabo"));
    _capitals.push_back(std::make_pair("Eritrea", "Asmara"));
    _capitals.push_back(std::make_pair("Estonia", "Tallinn"));
    _capitals.push_back(std::make_pair("Eswatini", "Mbabane"));
    _capitals.push_back(std::make_pair("Ethiopia", "Addis Ababa"));
    _capitals.push_back(std::make_pair("Fiji", "Suva"));
    _capitals.push_back(std::make_pair("Finland", "Helsinki"));
    _capitals.push_back(std::make_pair("France", "Paris"));
    _capitals.push_back(std::make_pair("Gabon", "Libreville"));
    _capitals.push_back(std::make_pair("Gambia", "Banjul"));
    _capitals.push_back(std::make_pair("Georgia", "Tbilisi"));
    _capitals.push_back(std::make_pair("Germany", "Berlin"));
    _capitals.push_back(std::make_pair("Ghana", "Accra"));
    _capitals.push_back(std::make_pair("Greece", "Athens"));
    _capitals.push_back(std::make_pair("Grenada", "Saint George's"));
    _capitals.push_back(std::make_pair("Guatemala", "Guatemala City"));
    _capitals.push_back(std::make_pair("Guinea", "Conakry"));
    _capitals.push_back(std::make_pair("Guinea-Bissau", "Bissau"));
    _capitals.push_back(std::make_pair("Guyana", "Georgetown"));
    _capitals.push_back(std::make_pair("Haiti", "Port-au-Prince"));
    _capitals.push_back(std::make_pair("Honduras", "Tegucigalpa"));
    _capitals.push_back(std::make_pair("Hungary", "Budapest"));
    _capitals.push_back(std::make_pair("Iceland", "Reykjavík"));
    _capitals.push_back(std::make_pair("India", "New Delhi"));
    _capitals.push_back(std::make_pair("Indonesia", "Jakarta"));
    _capitals.push_back(std::make_pair("Iran", "Tehran"));
    _capitals.push_back(std::make_pair("Iraq", "Baghdad"));
    _capitals.push_back(std::make_pair("Ireland", "Dublin"));
    _capitals.push_back(std::make_pair("Italy", "Rome"));
    _capitals.push_back(std::make_pair("Jamaica", "Kingston"));
    _capitals.push_back(std::make_pair("Japan", "Tokyo"));
    _capitals.push_back(std::make_pair("Jordan", "Amman"));
    _capitals.push_back(std::make_pair("Kazakhstan", "Astana"));
    _capitals.push_back(std::make_pair("Kenya", "Nairobi"));
    _capitals.push_back(std::make_pair("Kiribati", "Tarawa"));
    _capitals.push_back(std::make_pair("Kosovo", "Pristina"));
    _capitals.push_back(std::make_pair("Kuwait", "Kuwait City"));
    _capitals.push_back(std::make_pair("Kyrgyzstan", "Bishkek"));
    _capitals.push_back(std::make_pair("Laos", "Vientiane"));
    _capitals.push_back(std::make_pair("Latvia", "Riga"));
    _capitals.push_back(std::make_pair("Lebanon", "Beirut"));
    _capitals.push_back(std::make_pair("Lesotho", "Maseru"));
    _capitals.push_back(std::make_pair("Liberia", "Monrovia"));
    _capitals.push_back(std::make_pair("Libya", "Tripoli"));
    _capitals.push_back(std::make_pair("Liechtenstein", "Vaduz"));
    _capitals.push_back(std::make_pair("Lithuania", "Vilnius"));
    _capitals.push_back(std::make_pair("Luxembourg", "Luxembourg City"));
    _capitals.push_back(std::make_pair("Madagascar", "Antananarivo"));
    _capitals.push_back(std::make_pair("Malawi", "Lilongwe"));
    _capitals.push_back(std::make_pair("Malaysia", "Kuala Lumpur"));
    _capitals.push_back(std::make_pair("Maldives", "Malé"));
    _capitals.push_back(std::make_pair("Mali", "Bamako"));
    _capitals.push_back(std::make_pair("Malta", "Valletta"));
    _capitals.push_back(std::make_pair("Marshall Islands", "Majuro"));
    _capitals.push_back(std::make_pair("Mauritania", "Nouakchott"));
    _capitals.push_back(std::make_pair("Mauritius", "Port Louis"));
    _capitals.push_back(std::make_pair("Mexico", "Mexico City"));
    _capitals.push_back(std::make_pair("Micronesia", "Palikir"));
    _capitals.push_back(std::make_pair("Moldova", "Chișinău"));
    _capitals.push_back(std::make_pair("Monaco", "Monaco"));
    _capitals.push_back(std::make_pair("Mongolia", "Ulaanbaatar"));
    _capitals.push_back(std::make_pair("Montenegro", "Podgorica"));
    _capitals.push_back(std::make_pair("Morocco", "Rabat"));
    _capitals.push_back(std::make_pair("Mozambique", "Maputo"));
    _capitals.push_back(std::make_pair("Myanmar", "Naypyidaw"));
    _capitals.push_back(std::make_pair("Namibia", "Windhoek"));
    _capitals.push_back(std::make_pair("Nauru", "Yaren"));
    _capitals.push_back(std::make_pair("Nepal", "Kathmandu"));
    _capitals.push_back(std::make_pair("Netherlands", "Amsterdam"));
    _capitals.push_back(std::make_pair("New Zealand", "Wellington"));
    _capitals.push_back(std::make_pair("Nicaragua", "Managua"));
    _capitals.push_back(std::make_pair("Niger", "Niamey"));
    _capitals.push_back(std::make_pair("Nigeria", "Abuja"));
    _capitals.push_back(std::make_pair("North Korea", "Pyongyang"));
    _capitals.push_back(std::make_pair("North Macedonia", "Skopje"));
    _capitals.push_back(std::make_pair("Norway", "Oslo"));
    _capitals.push_back(std::make_pair("Oman", "Muscat"));
    _capitals.push_back(std::make_pair("Pakistan", "Islamabad"));
    _capitals.push_back(std::make_pair("Palau", "Ngerulmud"));
    _capitals.push_back(std::make_pair("Palestine", "Jerusalem"));
    _capitals.push_back(std::make_pair("Panama", "Panama City"));
    _capitals.push_back(std::make_pair("Papua New Guinea", "Port Moresby"));
    _capitals.push_back(std::make_pair("Paraguay", "Asunción"));
    _capitals.push_back(std::make_pair("Peru", "Lima"));
    _capitals.push_back(std::make_pair("Philippines", "Manila"));
    _capitals.push_back(std::make_pair("Poland", "Warsaw"));
    _capitals.push_back(std::make_pair("Portugal", "Lisbon"));
    _capitals.push_back(std::make_pair("Qatar", "Doha"));
    _capitals.push_back(std::make_pair("Romania", "Bucharest"));
    _capitals.push_back(std::make_pair("Russia", "Moscow"));
    _capitals.push_back(std::make_pair("Rwanda", "Kigali"));
    _capitals.push_back(std::make_pair("Saint Kitts and Nevis", "Basseterre"));
    _capitals.push_back(std::make_pair("Saint Lucia", "Castries"));
    _capitals.push_back(std::make_pair("Saint Vincent and the Grenadines", "Kingstown"));
    _capitals.push_back(std::make_pair("Samoa", "Apia"));
    _capitals.push_back(std::make_pair("San Marino", "San Marino"));
    _capitals.push_back(std::make_pair("São Tomé and Príncipe", "São Tomé"));
    _capitals.push_back(std::make_pair("Saudi Arabia", "Riyadh"));
    _capitals.push_back(std::make_pair("Senegal", "Dakar"));
    _capitals.push_back(std::make_pair("Serbia", "Belgrade"));
    _capitals.push_back(std::make_pair("Seychelles", "Victoria"));
    _capitals.push_back(std::make_pair("Sierra Leone", "Freetown"));
    _capitals.push_back(std::make_pair("Singapore", "Singapore"));
    _capitals.push_back(std::make_pair("Slovakia", "Bratislava"));
    _capitals.push_back(std::make_pair("Slovenia", "Ljubljana"));
    _capitals.push_back(std::make_pair("Solomon Islands", "Honiara"));
    _capitals.push_back(std::make_pair("Somalia", "Mogadishu"));
    _capitals.push_back(std::make_pair("South Africa", "Pretoria (administrative), Cape Town (legislative), Bloemfontein (judicial)"));
    _capitals.push_back(std::make_pair("South Korea", "Seoul"));
    _capitals.push_back(std::make_pair("South Sudan", "Juba"));
    _capitals.push_back(std::make_pair("Spain", "Madrid"));
    _capitals.push_back(std::make_pair("Sri Lanka", "Sri Jayawardenepura Kotte"));
    _capitals.push_back(std::make_pair("Sudan", "Khartoum"));
    _capitals.push_back(std::make_pair("Suriname", "Paramaribo"));
    _capitals.push_back(std::make_pair("Sweden", "Stockholm"));
    _capitals.push_back(std::make_pair("Switzerland", "Bern"));
    _capitals.push_back(std::make_pair("Syria", "Damascus"));
	_capitals.push_back(std::make_pair("Taiwan", "Taipei"));
    _capitals.push_back(std::make_pair("Tajikistan", "Dushanbe"));
    _capitals.push_back(std::make_pair("Tanzania", "Dodoma"));
    _capitals.push_back(std::make_pair("Thailand", "Bangkok"));
    _capitals.push_back(std::make_pair("Timor-Leste", "Dili"));
    _capitals.push_back(std::make_pair("Togo", "Lomé"));
    _capitals.push_back(std::make_pair("Tonga", "Nukuʻalofa"));
    _capitals.push_back(std::make_pair("Trinidad and Tobago", "Port of Spain"));
    _capitals.push_back(std::make_pair("Tunisia", "Tunis"));
    _capitals.push_back(std::make_pair("Turkey", "Ankara"));
    _capitals.push_back(std::make_pair("Turkmenistan", "Ashgabat"));
    _capitals.push_back(std::make_pair("Tuvalu", "Funafuti"));
    _capitals.push_back(std::make_pair("Uganda", "Kampala"));
    _capitals.push_back(std::make_pair("Ukraine", "Kyiv"));
    _capitals.push_back(std::make_pair("United Arab Emirates", "Abu Dhabi"));
    _capitals.push_back(std::make_pair("United Kingdom", "London"));
    _capitals.push_back(std::make_pair("United States", "Washington, D.C."));
    _capitals.push_back(std::make_pair("Uruguay", "Montevideo"));
    _capitals.push_back(std::make_pair("Uzbekistan", "Tashkent"));
    _capitals.push_back(std::make_pair("Vanuatu", "Port Vila"));
    _capitals.push_back(std::make_pair("Vatican City", "Vatican City"));
    _capitals.push_back(std::make_pair("Venezuela", "Caracas"));
    _capitals.push_back(std::make_pair("Vietnam", "Hanoi"));
    _capitals.push_back(std::make_pair("Yemen", "Sana'a"));
    _capitals.push_back(std::make_pair("Zambia", "Lusaka"));
    _capitals.push_back(std::make_pair("Zimbabwe", "Harare"));
}
